In [63]:
import numpy as np

In [65]:
np.__version__

'1.26.4'

In [67]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# creating list

In [70]:
my_list = [0,1,2,3,4,5]
my_list


[0, 1, 2, 3, 4, 5]

In [72]:
   type(my_list)

list

# code for converting list to array

In [75]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [77]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.arange(3.0)

array([0., 1., 2.])

In [81]:
np.arange(5.)

array([0., 1., 2., 3., 4.])

In [83]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [87]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [89]:
np.arange(20,10)

array([], dtype=int32)

In [91]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [93]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [95]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [97]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [99]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [101]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [103]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [105]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [107]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [109]:
zero = np.zeros([2,3])
print(zero)
print(type(zero))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [111]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [113]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [115]:
np.ones(3)

array([1., 1., 1.])

In [117]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [119]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [121]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [123]:
np.random.rand(5)

array([0.07863269, 0.95294413, 0.77993969, 0.19236186, 0.88086787])

In [125]:
np.random.rand(3,2)

array([[0.96082913, 0.52035174],
       [0.21848938, 0.57440607],
       [0.67927754, 0.41197982]])

In [127]:
np.random.randint(4,6)

5

In [129]:
np.random.randint(2,20,4)

array([18, 19,  6, 15])

In [131]:
np.random.randint(10,20,5)

array([10, 10, 11, 12, 19])

In [133]:
np.random.randint(10,40,(10,10))

array([[14, 19, 35, 18, 28, 22, 23, 19, 33, 25],
       [19, 39, 38, 32, 19, 27, 36, 19, 10, 38],
       [21, 18, 11, 25, 34, 16, 16, 32, 16, 14],
       [10, 36, 39, 38, 11, 29, 21, 34, 21, 25],
       [20, 27, 18, 39, 31, 15, 20, 29, 31, 16],
       [12, 36, 29, 35, 25, 25, 11, 31, 33, 27],
       [18, 30, 13, 15, 19, 25, 29, 36, 25, 23],
       [24, 10, 29, 38, 38, 16, 10, 23, 19, 12],
       [31, 14, 14, 29, 30, 20, 21, 21, 36, 30],
       [25, 11, 24, 29, 17, 35, 28, 17, 12, 23]])

In [135]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [137]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [139]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

# slicing in matrix

In [142]:
b = np.random.randint(10,20,(5,4))
b

array([[17, 15, 18, 11],
       [17, 11, 14, 12],
       [19, 18, 17, 10],
       [14, 15, 19, 18],
       [17, 18, 12, 10]])

In [144]:
type(b)

numpy.ndarray

In [146]:
b

array([[17, 15, 18, 11],
       [17, 11, 14, 12],
       [19, 18, 17, 10],
       [14, 15, 19, 18],
       [17, 18, 12, 10]])

In [148]:
b[:]

array([[17, 15, 18, 11],
       [17, 11, 14, 12],
       [19, 18, 17, 10],
       [14, 15, 19, 18],
       [17, 18, 12, 10]])

In [150]:
b[1:3]

array([[17, 11, 14, 12],
       [19, 18, 17, 10]])

In [152]:
b[1,2]

14

In [154]:
b[1,3]

12

In [156]:
b[1,-1]

12

In [158]:
b[2:3]

array([[19, 18, 17, 10]])

In [160]:
b[0:-2]

array([[17, 15, 18, 11],
       [17, 11, 14, 12],
       [19, 18, 17, 10]])

In [162]:
b[0,2]

18

In [164]:
b[-5,-3]

15

In [166]:
b[-5,-3]

15

In [168]:
b[-4,2]

14

# operations

In [171]:
a = np.random.randint(10,20,10)
a

array([19, 18, 17, 14, 14, 15, 13, 14, 14, 18])

In [173]:
id(a)

1934376404624

In [175]:
arr

array([0, 1, 2, 3, 4, 5])

In [177]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[37,  7, 58, 52, 11, 13, 44, 76, 60, 60],
       [ 4, 27, 16, 75,  7, 52, 47, 61,  5, 73],
       [25, 64, 57, 12, 27, 82, 51, 54, 94, 76],
       [50, 61, 99, 16, 90, 81,  6, 61, 17, 89],
       [43, 89, 74, 57, 43, 15, 58, 18, 58, 91],
       [45, 97, 90, 75, 34, 98, 56, 71, 20, 25],
       [18, 89, 92, 82, 43, 23, 39, 26,  2, 31],
       [34, 97, 94, 93, 81, 37, 28, 31, 48, 71],
       [80,  3, 60, 24, 18, 46, 77, 75, 75,  8],
       [ 2, 85, 92, 27, 97, 40, 36, 74, 83, 71]])

In [179]:
arr

array([0, 1, 2, 3, 4, 5])

In [181]:
arr[:4]

array([0, 1, 2, 3])

In [183]:
arr2[:]

array([[37,  7, 58, 52, 11, 13, 44, 76, 60, 60],
       [ 4, 27, 16, 75,  7, 52, 47, 61,  5, 73],
       [25, 64, 57, 12, 27, 82, 51, 54, 94, 76],
       [50, 61, 99, 16, 90, 81,  6, 61, 17, 89],
       [43, 89, 74, 57, 43, 15, 58, 18, 58, 91],
       [45, 97, 90, 75, 34, 98, 56, 71, 20, 25],
       [18, 89, 92, 82, 43, 23, 39, 26,  2, 31],
       [34, 97, 94, 93, 81, 37, 28, 31, 48, 71],
       [80,  3, 60, 24, 18, 46, 77, 75, 75,  8],
       [ 2, 85, 92, 27, 97, 40, 36, 74, 83, 71]])

In [185]:
arr2[0:5]

array([[37,  7, 58, 52, 11, 13, 44, 76, 60, 60],
       [ 4, 27, 16, 75,  7, 52, 47, 61,  5, 73],
       [25, 64, 57, 12, 27, 82, 51, 54, 94, 76],
       [50, 61, 99, 16, 90, 81,  6, 61, 17, 89],
       [43, 89, 74, 57, 43, 15, 58, 18, 58, 91]])

In [187]:
arr2

array([[37,  7, 58, 52, 11, 13, 44, 76, 60, 60],
       [ 4, 27, 16, 75,  7, 52, 47, 61,  5, 73],
       [25, 64, 57, 12, 27, 82, 51, 54, 94, 76],
       [50, 61, 99, 16, 90, 81,  6, 61, 17, 89],
       [43, 89, 74, 57, 43, 15, 58, 18, 58, 91],
       [45, 97, 90, 75, 34, 98, 56, 71, 20, 25],
       [18, 89, 92, 82, 43, 23, 39, 26,  2, 31],
       [34, 97, 94, 93, 81, 37, 28, 31, 48, 71],
       [80,  3, 60, 24, 18, 46, 77, 75, 75,  8],
       [ 2, 85, 92, 27, 97, 40, 36, 74, 83, 71]])

In [189]:
arr2[1,4]

7

In [191]:
arr2

array([[37,  7, 58, 52, 11, 13, 44, 76, 60, 60],
       [ 4, 27, 16, 75,  7, 52, 47, 61,  5, 73],
       [25, 64, 57, 12, 27, 82, 51, 54, 94, 76],
       [50, 61, 99, 16, 90, 81,  6, 61, 17, 89],
       [43, 89, 74, 57, 43, 15, 58, 18, 58, 91],
       [45, 97, 90, 75, 34, 98, 56, 71, 20, 25],
       [18, 89, 92, 82, 43, 23, 39, 26,  2, 31],
       [34, 97, 94, 93, 81, 37, 28, 31, 48, 71],
       [80,  3, 60, 24, 18, 46, 77, 75, 75,  8],
       [ 2, 85, 92, 27, 97, 40, 36, 74, 83, 71]])

In [193]:
arr2[-5,-5]

98

In [195]:
arr2[-5,5]

98

In [197]:
arr2[-1,-2]

83

In [199]:
arr2[::-1]

array([[ 2, 85, 92, 27, 97, 40, 36, 74, 83, 71],
       [80,  3, 60, 24, 18, 46, 77, 75, 75,  8],
       [34, 97, 94, 93, 81, 37, 28, 31, 48, 71],
       [18, 89, 92, 82, 43, 23, 39, 26,  2, 31],
       [45, 97, 90, 75, 34, 98, 56, 71, 20, 25],
       [43, 89, 74, 57, 43, 15, 58, 18, 58, 91],
       [50, 61, 99, 16, 90, 81,  6, 61, 17, 89],
       [25, 64, 57, 12, 27, 82, 51, 54, 94, 76],
       [ 4, 27, 16, 75,  7, 52, 47, 61,  5, 73],
       [37,  7, 58, 52, 11, 13, 44, 76, 60, 60]])

In [201]:
arr2

array([[37,  7, 58, 52, 11, 13, 44, 76, 60, 60],
       [ 4, 27, 16, 75,  7, 52, 47, 61,  5, 73],
       [25, 64, 57, 12, 27, 82, 51, 54, 94, 76],
       [50, 61, 99, 16, 90, 81,  6, 61, 17, 89],
       [43, 89, 74, 57, 43, 15, 58, 18, 58, 91],
       [45, 97, 90, 75, 34, 98, 56, 71, 20, 25],
       [18, 89, 92, 82, 43, 23, 39, 26,  2, 31],
       [34, 97, 94, 93, 81, 37, 28, 31, 48, 71],
       [80,  3, 60, 24, 18, 46, 77, 75, 75,  8],
       [ 2, 85, 92, 27, 97, 40, 36, 74, 83, 71]])

In [203]:
arr2[::-2]

array([[ 2, 85, 92, 27, 97, 40, 36, 74, 83, 71],
       [34, 97, 94, 93, 81, 37, 28, 31, 48, 71],
       [45, 97, 90, 75, 34, 98, 56, 71, 20, 25],
       [50, 61, 99, 16, 90, 81,  6, 61, 17, 89],
       [ 4, 27, 16, 75,  7, 52, 47, 61,  5, 73]])

In [205]:
arr2

array([[37,  7, 58, 52, 11, 13, 44, 76, 60, 60],
       [ 4, 27, 16, 75,  7, 52, 47, 61,  5, 73],
       [25, 64, 57, 12, 27, 82, 51, 54, 94, 76],
       [50, 61, 99, 16, 90, 81,  6, 61, 17, 89],
       [43, 89, 74, 57, 43, 15, 58, 18, 58, 91],
       [45, 97, 90, 75, 34, 98, 56, 71, 20, 25],
       [18, 89, 92, 82, 43, 23, 39, 26,  2, 31],
       [34, 97, 94, 93, 81, 37, 28, 31, 48, 71],
       [80,  3, 60, 24, 18, 46, 77, 75, 75,  8],
       [ 2, 85, 92, 27, 97, 40, 36, 74, 83, 71]])

In [207]:
arr2[::-3]

array([[ 2, 85, 92, 27, 97, 40, 36, 74, 83, 71],
       [18, 89, 92, 82, 43, 23, 39, 26,  2, 31],
       [50, 61, 99, 16, 90, 81,  6, 61, 17, 89],
       [37,  7, 58, 52, 11, 13, 44, 76, 60, 60]])

In [209]:
arr2

array([[37,  7, 58, 52, 11, 13, 44, 76, 60, 60],
       [ 4, 27, 16, 75,  7, 52, 47, 61,  5, 73],
       [25, 64, 57, 12, 27, 82, 51, 54, 94, 76],
       [50, 61, 99, 16, 90, 81,  6, 61, 17, 89],
       [43, 89, 74, 57, 43, 15, 58, 18, 58, 91],
       [45, 97, 90, 75, 34, 98, 56, 71, 20, 25],
       [18, 89, 92, 82, 43, 23, 39, 26,  2, 31],
       [34, 97, 94, 93, 81, 37, 28, 31, 48, 71],
       [80,  3, 60, 24, 18, 46, 77, 75, 75,  8],
       [ 2, 85, 92, 27, 97, 40, 36, 74, 83, 71]])

In [211]:
arr2[0:10:3]

array([[37,  7, 58, 52, 11, 13, 44, 76, 60, 60],
       [50, 61, 99, 16, 90, 81,  6, 61, 17, 89],
       [18, 89, 92, 82, 43, 23, 39, 26,  2, 31],
       [ 2, 85, 92, 27, 97, 40, 36, 74, 83, 71]])

In [213]:
arr

array([0, 1, 2, 3, 4, 5])

In [215]:
arr.max()

5

In [217]:
arr.min()

0

In [219]:
arr.mean()

2.5

In [221]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [223]:
from numpy import * # 256 functions has been called internally
a = array([1,2,3,4,9,6])
median(a)

3.5

# without work on import* can you please find median,mode

In [226]:
arr

array([0, 1, 2, 3, 4, 5])

In [228]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [230]:
arr.reshape()

TypeError: reshape() takes exactly 1 argument (0 given)

In [232]:
arr.reshape(3,2,order = 'c')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [234]:
arr.reshape(2,3,order='F') # print element with fortron

array([[0, 2, 4],
       [1, 3, 5]])

In [236]:
arr.reshape(2,3,order='A') # a almost gives you c type ouput

array([[0, 1, 2],
       [3, 4, 5]])

# indexing

In [244]:
mat = np.arange(0,100).reshape(10,10)
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [248]:
row = 4
col = 5
col

5

In [250]:
row

4

In [252]:
mat[row,col]

45

In [254]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [260]:
mat[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [262]:
mat[1:2,2:3]

array([[12]])

In [264]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [266]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

# masking

In [269]:
mat #

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [271]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [273]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [275]:
mat[mat==50]

array([50])

In [277]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [279]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])